name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK (RuStore)
        run: flutter build apk --release --flavor rustore

      - name: Build AppBundle (RuStore)
        run: flutter build appbundle --release --flavor rustore

      - name: Build AppBundle (Google Play)
        run: flutter build appbundle --release --flavor gplay --dart-define=STORE=gplay

      - name: Upload APK (RuStore)
        uses: actions/upload-artifact@v4
        with:
          name: apk-rustore-release
          path: build/app/outputs/flutter-apk/app-rustore-release.apk

      - name: Upload AppBundle (RuStore)
        uses: actions/upload-artifact@v4
        with:
          name: aab-rustore-release
          path: build/app/outputs/bundle/rustoreRelease/app-rustore-release.aab

      - name: Upload AppBundle (Google Play)
        uses: actions/upload-artifact@v4
        with:
          name: aab-gplay-release
          path: build/app/outputs/bundle/gplayRelease/app-gplay-release.aab

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web